HOW_MANY_ELEVATORS = 10

LIFETIME_OF_ELEVATOR= 365

SINGLE_ELEVATOR_PRICE = 30000


# In days
AVERAGE_REPAIR_TIME = 2
REPAIR_TIME_VARIANCE = 0.1

# For new parts/fixing the old parts
MINIMUM_REPAIR_COST = 0
MAXIMUM_REPAIR_COST = 2000


# Just for calling the repair service and making them come around
REPAIR_COST_CONST = 120
REPAIR_COST_PER_DAY = 75 * 8

ANNUAL_CHECK_COST = 150

FULL_LIFETIME_ELEVATOR_PRICE = SINGLE_ELEVATOR_PRICE + ANNUAL_CHECK_COST * 25